#!/bin/bash
# upload_ollama_model.sh
# Package a local GGUF file into an Ollama model and (optionally) push it.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEFAULT_GGUF="$REPO_ROOT/data/output/gguf/lca-qwen3-st-finetuned-f16.gguf"
FALLBACK_GGUF="$REPO_ROOT/data/output/gguf/lca-qwen3-st-finetuned-f16.gguf"

MODEL_NAME="${MODEL_NAME:-lca-bge-m3-ft}"
GGUF_PATH="${GGUF_PATH:-$DEFAULT_GGUF}"
BUILD_DIR="${BUILD_DIR:-$REPO_ROOT/data/output/ollama/$MODEL_NAME}"
MOD_TEMPLATE="${MOD_TEMPLATE:-""}"
SYSTEM_PROMPT="${SYSTEM_PROMPT:-"You are a fine-tuned BGE-M3 embedding model exposed via Ollama."}"
OLLAMA_BIN="${OLLAMA_BIN:-ollama}"
PUSH_TARGET="${PUSH_TARGET:-}" # e.g. user/lca-bge-m3-ft

if [[ ! -f "$GGUF_PATH" ]]; then
  if [[ -f "$FALLBACK_GGUF" ]]; then
    echo "[WARN] GGUF not found at $GGUF_PATH, falling back to $FALLBACK_GGUF"
    GGUF_PATH="$FALLBACK_GGUF"
  else
    echo "[ERROR] GGUF file not found. Set GGUF_PATH to a valid file." >&2
    exit 1
  fi
fi

if ! command -v "$OLLAMA_BIN" >/dev/null 2>&1; then
  echo "[ERROR] Ollama CLI ($OLLAMA_BIN) not found in PATH." >&2
  exit 1
fi

mkdir -p "$BUILD_DIR"
GGUF_DEST="$BUILD_DIR/$(basename "$GGUF_PATH")"
cp -f "$GGUF_PATH" "$GGUF_DEST"

MODELPATH="$BUILD_DIR/Modelfile"
{
  echo "# Generated by scripts/upload_ollama_model.sh"
  echo "FROM ./$(basename "$GGUF_DEST")"
  if [[ -n "$MOD_TEMPLATE" ]]; then
    echo ""
    echo 'TEMPLATE """'"$MOD_TEMPLATE"'"""'
  fi
  echo ""
  echo 'SYSTEM """'"$SYSTEM_PROMPT"'"""'
  echo ""
  echo "PARAMETER num_ctx 2048"
} >"$MODELPATH"

echo "============================================================"
echo "Ollama model packaging"
echo "============================================================"
echo "Model name : $MODEL_NAME"
echo "GGUF source: $GGUF_PATH"
echo "Build dir  : $BUILD_DIR"
echo "Push target: ${PUSH_TARGET:-<skip>}"

echo -e "\n[1/2] Creating/Updating Ollama model..."
$OLLAMA_BIN create "$MODEL_NAME" -f "$MODELPATH"

if [[ -n "$PUSH_TARGET" ]]; then
  echo -e "\n[2/2] Pushing to $PUSH_TARGET ..."
  if [[ "$PUSH_TARGET" != "$MODEL_NAME" ]]; then
    echo "Creating temporary Modelfile for push alias..."
    PUSH_BUILD_DIR="$BUILD_DIR-push"
    mkdir -p "$PUSH_BUILD_DIR"
    cat >"$PUSH_BUILD_DIR/Modelfile" <<EOF
# Auto-generated for push alias
FROM $(basename "$GGUF_DEST")
EOF
    (cd "$PUSH_BUILD_DIR" && cp -f "$GGUF_DEST" . && $OLLAMA_BIN create "$PUSH_TARGET" -f Modelfile)
    TARGET_NAME="$PUSH_TARGET"
  else
    TARGET_NAME="$MODEL_NAME"
  fi
  $OLLAMA_BIN push "$TARGET_NAME"
else
  echo -e "\n[2/2] Push skipped (set PUSH_TARGET to enable)."
fi

echo -e "\nDone. Test with: $OLLAMA_BIN run $MODEL_NAME"
